### ISSUE TITLE
PF2E LootGen requires PF2E Toolbox to work, but is isn't set up as dependency

### ISSUE THREAD

**Issue by Ustin** [Djphoenix719/FVTT-PF2ELootGen#2]
Title. If Toolbox isn't installed It throws some error in console about setting not being registered instead of generating loot. 

Probably should be set up as dependency in Foundry, so Foundry would prevent it from being used in broken state.  

Alternatively shouldn't require another module to be installed.

**Comment by Djphoenix719** [comment]
Hi thanks for the report @Ustin - this is a good catch, I'll ensure the module works without Toolbox next update. I could specify that they require each other but I doubt the dependency system can resolve circular dependencies at the moment.
